categories:
- Sequence Analysis
- Assembly
- Metagenomics
description: Galaxy wrapper for Megahit_toolkit contig2fastg
homepage_url: https://github.com/voutcn/megahit/blob/master/tools/toolkit.cpp
long_description: |
    MEGAHIT is a single node assembler for large and complex metagenomics NGS reads, such as soil. It makes use of succinct de Bruijn graph (SdBG) to achieve low memory assembly. MEGAHIT can optionally utilize a CUDA-enabled GPU to accelerate its SdBG contstruction. The GPU-accelerated version of MEGAHIT has been tested on NVIDIA GTX680 (4G memory) and Tesla K40c (12G memory) with CUDA 5.5, 6.0 and 6.5. MEGAHIT v1.0 or greater also supports IBM Power PC and has been tested on IBM POWER8.
name: megahit
owner: galaxyp
remote_repository_url: https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/megahit_contig2fastg
type: unrestricted