categories:
- Sequence Analysis
- Assembly
- Metagenomics
description: A subprogram within the Megahit toolkit for converting contigs to assembly graphs (fastg)
homepage_url: https://github.com/voutcn/megahit/blob/master/tools/toolkit.cpp
long_description: |
    Contig2fastg MEGAHIT is a single node assembler for large and complex metagenomics NGS reads, such as soil. It makes use of succinct de Bruijn graph (SdBG) to achieve low memory assembly. MEGAHIT can optionally utilize a CUDA-enabled GPU to accelerate its SdBG contstruction. The GPU-accelerated version of MEGAHIT has been tested on NVIDIA GTX680 (4G memory) and Tesla K40c (12G memory) with CUDA 5.5, 6.0 and 6.5. MEGAHIT v1.0 or greater also supports IBM Power PC and has been tested on IBM POWER8.
name: megahit_contig2fastg
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/blob/master/tools/megahit_contig2fastg
type: unrestricted